version: "3"

services:
  app:
    image: htillero/swarm-networking
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000:3000"
    deploy:
      placement:
        constraints: [node.role==worker]  

  db:
    image: mongo:4.0.4
    deploy:
      placement:
        constraints: [node.role==worker]

  viz:
      image: dockersamples/visualizer
      ports:
        - "8080:8080"
      deploy:
        placement:
          constraints: [node.role==manager]
      source: 
        /var/run/docker.sock
      dst:
        /var/run/docker.sock"
